version: '3.8'

services:

  api:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000


  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6370:6379

