# Generated by Django 4.2.1 on 2023-05-10 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mame', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Plan_row',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_row', models.IntegerField()),
                ('col_0', models.CharField(max_length=200, null=True, verbose_name='Сводный код объекта ремонта (X/Y/Z)')),
                ('col_1', models.CharField(max_length=200, null=True, verbose_name='рег. № договора с ГИ-ГР')),
                ('col_2', models.CharField(max_length=200, null=True, verbose_name='Принципал')),
                ('col_3', models.CharField(max_length=200, null=True, verbose_name='Подразделение Принципала (ЛПУ, УПХГ, УГПГ, Завод и т.д.)')),
                ('col_4', models.CharField(max_length=200, null=True, verbose_name='Наименование объекта Диагностирования')),
                ('col_5', models.CharField(max_length=200, null=True, verbose_name='Наименование объекта диагностирования согласно карточке учета ОС')),
                ('col_6', models.CharField(max_length=200, null=True, verbose_name='Вид работ')),
                ('col_7', models.CharField(max_length=200, null=True, verbose_name='Содержание работ')),
                ('col_8', models.CharField(max_length=200, null=True, verbose_name='Инв. Номер')),
                ('col_9', models.CharField(max_length=200, null=True, verbose_name='Ед. изкмерения')),
                ('col_10', models.CharField(max_length=200, null=True, verbose_name='Кол-во')),
                ('col_11', models.CharField(max_length=200, null=True, verbose_name='Куратор')),
                ('col_12', models.CharField(max_length=200, null=True, verbose_name='Исполнители полевых работ')),
                ('col_13', models.CharField(max_length=200, null=True, verbose_name='Ведущий инженер КО')),
                ('col_14', models.CharField(max_length=200, null=True, verbose_name='Инженер КО')),
                ('col_15', models.CharField(max_length=200, null=True, verbose_name='Сметчик')),
                ('col_16', models.CharField(max_length=200, null=True, verbose_name='Стоимость работ, руб.')),
                ('col_17', models.CharField(max_length=200, null=True, verbose_name='I квартал')),
                ('col_18', models.CharField(max_length=200, null=True, verbose_name='II квартал')),
                ('col_19', models.CharField(max_length=200, null=True, verbose_name='III квартал')),
                ('col_20', models.CharField(max_length=200, null=True, verbose_name='IV квартал')),
                ('col_21', models.CharField(max_length=200, null=True, verbose_name='Исполнитель')),
                ('col_22', models.CharField(max_length=200, null=True, verbose_name='Соисполнитель')),
                ('col_23', models.CharField(max_length=200, null=True, verbose_name='Принадлежность к договору (ОСН, ДС1, ДС2 и т.д.)')),
                ('col_24', models.CharField(max_length=200, null=True, verbose_name='Стоимость работ Соисполнителя, руб без НДС')),
                ('col_25', models.CharField(max_length=200, null=True, verbose_name='ФАКТ')),
                ('col_26', models.CharField(max_length=200, null=True, verbose_name='Процент выполнения')),
                ('col_27', models.CharField(max_length=200, null=True, verbose_name='Финансовый акт, сумма без НДС в руб Полевой этап')),
                ('col_28', models.CharField(max_length=200, null=True, verbose_name='Финансовый акт, сумма без НДС в руб Камеральный этап')),
                ('col_29', models.CharField(max_length=200, null=True, verbose_name='ИТОГО выполнено работ, в руб без НДС Полевой+камеральный этап')),
                ('col_30', models.CharField(max_length=200, null=True, verbose_name='График производства работ')),
                ('col_31', models.CharField(max_length=200, null=True, verbose_name='Программа производства работ')),
                ('col_32', models.CharField(max_length=200, null=True, verbose_name='Допуск к производству работ')),
                ('col_33', models.CharField(max_length=200, null=True, verbose_name='Дата начала работ')),
                ('col_34', models.CharField(max_length=200, null=True, verbose_name='Дата окончания работ')),
                ('col_35', models.CharField(max_length=200, null=True, verbose_name='Дата начала работ Факт')),
                ('col_36', models.CharField(max_length=200, null=True, verbose_name='Дата окончания работ Факт')),
                ('col_37', models.CharField(max_length=200, null=True, verbose_name='Статус работ')),
                ('col_38', models.CharField(max_length=200, null=True, verbose_name='Выполнение физических объемов работ ФАКТ, ед.изм.')),
                ('col_39', models.CharField(max_length=200, null=True, verbose_name='Технический акт выполненных работ')),
                ('col_40', models.CharField(max_length=200, null=True, verbose_name='Приборы')),
                ('col_41', models.CharField(max_length=200, null=True, verbose_name='Автомобиль')),
                ('col_42', models.CharField(max_length=200, null=True, verbose_name='Дата выезда в командировку')),
                ('col_43', models.CharField(max_length=200, null=True, verbose_name='Дата возврата из командировки')),
                ('col_44', models.CharField(max_length=200, null=True, verbose_name='Технический отчет/Паспорт/Отчет о технич состоянии ПЛАН, шт.')),
                ('col_45', models.CharField(max_length=200, null=True, verbose_name='Технический отчет/Паспорт/Отчет о технич состоянии ПЕРЕДАНО ЗАКАЗЧИКУ НА СОГЛАСОВАНИЕ, шт.')),
                ('col_46', models.CharField(max_length=200, null=True, verbose_name='Технический отчет/Паспорт/Отчет о технич состоянии ОФОРМЛЕНО И СДАНО ЗАКАЗЧИКУ, шт.')),
                ('col_47', models.CharField(max_length=200, null=True, verbose_name='Технический отчет/Паспорт/Отчет о технич состоянии ДАТА СДАЧИ ПЛАН')),
                ('col_48', models.CharField(max_length=200, null=True, verbose_name='Технический отчет/Паспорт/Отчет о технич состоянии ДАТА СДАЧИ ФАКТ')),
                ('col_49', models.CharField(max_length=200, null=True, verbose_name='ЗЭПБ ПЛАН, шт.')),
                ('col_50', models.CharField(max_length=200, null=True, verbose_name='ЗЭПБ ПЛАН, дата сдачи по графику')),
                ('col_51', models.CharField(max_length=200, null=True, verbose_name='ЗЭПБ ФАКТ (передано Заказчику на согласование), шт.')),
                ('col_52', models.CharField(max_length=200, null=True, verbose_name='ЗЭПБ ФАКТ (оформлено и сдано Заказчику), шт.')),
                ('col_53', models.CharField(max_length=200, null=True, verbose_name='ЗЭПБ ФАКТ, дата сдачи')),
                ('col_54', models.CharField(max_length=200, null=True, verbose_name='ЗЭПБ ФАКТ ПЕРЕДАНО НА РЕГИСТРАЦИЮ В РТН, шт.')),
                ('col_55', models.CharField(max_length=200, null=True, verbose_name='ЗЭПБ ФАКТ ЗАРЕГИСТРИРО-ВАНО В РТН, шт.')),
                ('col_56', models.CharField(max_length=200, null=True, verbose_name='ЗЭПБ ФАКТ, дата регистрации')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_row', to='megaboss_app.plan')),
            ],
        ),
    ]
