# Generated by Django 4.2.1 on 2023-06-17 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('megaboss_app', '0004_auto_20230617_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollumsUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collum', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collum', to='megaboss_app.collums')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
