# Generated by Django 4.2.1 on 2023-06-18 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('megaboss_app', '0005_collumsuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CollumsUser',
        ),
    ]
